### ISSUE TITLE
Trap signals with run-parts

### ISSUE THREAD

**Issue by tarantegui** [pataquets/cloe_run#1]
My docker container is running cloe_run with run-parts. Then I send a SIGTERM signal to it but it not responds. I'm only able to stop it with a SIGKILL on a sleep window.

Thank you!

**Comment by pataquets** [comment]
I could not reproduce the issue. Can you provide a specific example/script?

**Comment by tarantegui** [comment]
I've found the solution to the problem! Run parts need the programs inside folder to be without extensions. 

So, there is no problem with cloe_run.
